language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - nightly

env:
  - SYMFONY_VERSION=2.7.* SYMFONY_DEPRECATIONS_HELPER=weak

install: composer install --dev --prefer-source

notifications:
  email: "douglas@usemarkup.com"

matrix:
  allow_failures:
    - php: nightly
